name: Latest blog post workflow

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch: 

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Pull in latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.imcry.vip/index.xml"
          max_post_count: 10
          user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36"
          
          
          readme_path: "./README.MD"
